micronaut:
  application:
    name: cassandraMicronaut
netty:
  default:
    allocator:
      max-order: 3
cassandra:
  default:
    clusterName: '"myCluster"'
    contactPoint: '"localhost"'
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true
